// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6Qi6bnNi1rpnzUfubSu6Kme0u8seXl7w',
    appId: '1:791349829931:web:d26332a09d9f2edb1de56e',
    messagingSenderId: '791349829931',
    projectId: 'barbershopplg',
    authDomain: 'barbershopplg.firebaseapp.com',
    storageBucket: 'barbershopplg.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvxs58diQlr1qJ9sT9i7takwMHtFiB3hI',
    appId: '1:791349829931:android:8bb9b82bd795cc9b1de56e',
    messagingSenderId: '791349829931',
    projectId: 'barbershopplg',
    storageBucket: 'barbershopplg.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB_XUluHK-QvEY_hcZGmJPj5Gx6idzRhY',
    appId: '1:791349829931:ios:1d9285697ce8cbdc1de56e',
    messagingSenderId: '791349829931',
    projectId: 'barbershopplg',
    storageBucket: 'barbershopplg.appspot.com',
    iosBundleId: 'com.example.barbershopplg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCB_XUluHK-QvEY_hcZGmJPj5Gx6idzRhY',
    appId: '1:791349829931:ios:1d9285697ce8cbdc1de56e',
    messagingSenderId: '791349829931',
    projectId: 'barbershopplg',
    storageBucket: 'barbershopplg.appspot.com',
    iosBundleId: 'com.example.barbershopplg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6Qi6bnNi1rpnzUfubSu6Kme0u8seXl7w',
    appId: '1:791349829931:web:1f6c233e4975b77b1de56e',
    messagingSenderId: '791349829931',
    projectId: 'barbershopplg',
    authDomain: 'barbershopplg.firebaseapp.com',
    storageBucket: 'barbershopplg.appspot.com',
  );
}
